// <auto-generated />
using System;
using IS413_Temple_Signup_ZS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS413_Temple_Signup_ZS.Migrations
{
    [DbContext(typeof(tourGroupContext))]
    partial class tourGroupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("IS413_Temple_Signup_ZS.Models.timeSlot", b =>
                {
                    b.Property<int>("slotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("availablility")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("scheduleInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("slotID");

                    b.ToTable("timeSlots");
                });

            modelBuilder.Entity("IS413_Temple_Signup_ZS.Models.tourGroup", b =>
                {
                    b.Property<int>("groupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("groupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("groupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("groupID");

                    b.ToTable("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
